apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: adlrecorder
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: adlrecorder
            image: f73-g1.cloudogu.net/nexus/hektor/adl-recorder:latest
            ports:
            - name: http
              containerPort: 8080
            env:
            - name: ADL_BACKEND_IP
              value: adlbackendservice
          imagePullSecrets:
          - name: dockreg
          restartPolicy: Never
