apiVersion: apps/v1
kind: Deployment
metadata:
  name: adlrecorder
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: adlrecorder
  template:
    metadata:
      labels:
        app: adlrecorder
    spec:
      containers:
        - name: adlrecorder
          image: f73-g2.cloudogu.net/achilles/adlrecorder
          ports:
            - name: http
              containerPort: 8080
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: adlrecorder
  namespace: default
  labels:
    app: adlrecorder
spec:
  selector:
    app: adlrecorder
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080