apiVersion: apps/v1
kind: Deployment
metadata:
  name: adlfrontend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: adlfrontend
  template:
    metadata:
      labels:
        app: adlfrontend
    spec:
      containers:
        - name: adlfrontend
          image: f73-g2.cloudogu.net/achilles/adlfrontend
          ports:
            - name: http
              containerPort: 80
          env:
            - name: IMPORT-SERVICE-CLUSTERIP
              value: 34.69.127.37
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: adlfrontend
  namespace: default
  labels:
    app: adlfrontend
spec:
  selector:
    app: adlfrontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
